### ISSUE TITLE
Constraint AASd-109 not checked correctly

### ISSUE THREAD

**Issue by otto-ifak** [aas-core-works/aas-core3.0-csharp#38] opened 2024-08-22 08:08 UTC
According to the spec:

Constraint AASd-109: If SubmodelElementList/typeValueListElement is equal to
Property or Range, SubmodelElementList/valueTypeListElement shall be set and
all first level child elements in the SubmodelElementList shall have the value type
as specified in SubmodelElementList/valueTypeListElement.

This means, that the following JSON should be rejected due to the missing `valueTypeListElement`:

```json
{
    "submodels": [
        {
            "modelType": "Submodel",
            "id": "x",
            "submodelElements": [
                {
                    "idShort": "x",
                    "modelType": "SubmodelElementList",
                    "typeValueListElement": "Property"
                }
            ]
        }
    ]
}
```

However, it is accepted.

**Comment by mristin** [comment] 2024-08-22 09:13
Hi @otto-ifak ,
I think we got it wrong for the case when `value` attribute is not set. Can you please double-check the current specification:
https://github.com/aas-core-works/aas-core-meta/blob/31d6afd348a86f43cc658cc5bffab49f1e47bd24/aas_core_meta/v3.py#L2655

@s-heppner @zrgt can you please double-check as well?

**Comment by otto-ifak** [comment] 2024-08-22 10:51
@mristin To be honest, I am not sure how to formalize this correctly as I find the invariant hard to read. I agree, that the problem is caused by the missing `value` attribute, because it rejects the sample above correctly when I am adding the `value` attribute.

**Comment by mristin** [comment] 2024-08-22 12:01
@otto-ifak can you please then double-check my change suggestion above?

**Comment by zrgt** [comment] 2024-08-22 18:21
@mristin @otto-ifak , as far as I can see, the problem was indeed caused by the not set value. The suggestion of @mristin should fix it.

**Comment by mristin** [comment] 2024-08-23 09:07
@s-heppner can you please have a look?

**Comment by mristin** [comment] 2024-08-27 07:31
@otto-ifak I generated the code with a fixed meta-model on: https://github.com/aas-core-works/aas-core3.0-python/tree/mristin/Test-fixed-AASd-109

Can you please run your test battery against that branch? Once we confirm that it works on Python SDK, I'll propagate to all the other SDKs. (C# SDK takes a bit longer to generate & compile, so I chose Python.)

**Comment by otto-ifak** [comment] 2024-08-27 20:11
Python SDK seems to be fine, I have found some bugs in the csharp SDK, though. I will investigate them and create issues accordingly.

**Comment by otto-ifak** [comment] 2024-08-27 20:46
Everything fine, except for https://github.com/aas-core-works/aas-core3.0-csharp/issues/41

**Comment by s-heppner** [comment] 2024-08-30 07:35
I also think this should fix it.

**Comment by mristin** [comment] 2024-08-31 11:59
Closing, fixed and propagated in all the SDKs.

@otto-ifak please double-check with some of the SDKs.

**Closed by mristin** 2024-08-31 11:59 UTC
